'
' * Copyright (c) 2005, 2013, Oracle and/or its affiliates. All rights reserved.
' * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' 

Namespace javax.sql


	''' <summary>
	''' Interface that defines the methods which are common between <code>DataSource</code>,
	''' <code>XADataSource</code> and <code>ConnectionPoolDataSource</code>.
	''' 
	''' </summary>
	Public Interface CommonDataSource

		''' <summary>
		''' <p>Retrieves the log writer for this <code>DataSource</code>
		''' object.
		''' 
		''' <p>The log writer is a character output stream to which all logging
		''' and tracing messages for this data source will be
		''' printed.  This includes messages printed by the methods of this
		''' object, messages printed by methods of other objects manufactured
		''' by this object, and so on.  Messages printed to a data source
		''' specific log writer are not printed to the log writer associated
		''' with the <code>java.sql.DriverManager</code> class.  When a
		''' <code>DataSource</code> object is
		''' created, the log writer is initially null; in other words, the
		''' default is for logging to be disabled.
		''' </summary>
		''' <returns> the log writer for this data source or null if
		'''        logging is disabled </returns>
		''' <exception cref="java.sql.SQLException"> if a database access error occurs </exception>
		''' <seealso cref= #setLogWriter
		''' @since 1.4 </seealso>
		Property logWriter As java.io.PrintWriter


		''' <summary>
		''' <p>Sets the maximum time in seconds that this data source will wait
		''' while attempting to connect to a database.  A value of zero
		''' specifies that the timeout is the default system timeout
		''' if there is one; otherwise, it specifies that there is no timeout.
		''' When a <code>DataSource</code> object is created, the login timeout is
		''' initially zero.
		''' </summary>
		''' <param name="seconds"> the data source login time limit </param>
		''' <exception cref="SQLException"> if a database access error occurs. </exception>
		''' <seealso cref= #getLoginTimeout
		''' @since 1.4 </seealso>
		Property loginTimeout As Integer


		'------------------------- JDBC 4.1 -----------------------------------

		''' <summary>
		''' Return the parent Logger of all the Loggers used by this data source. This
		''' should be the Logger farthest from the root Logger that is
		''' still an ancestor of all of the Loggers used by this data source. Configuring
		''' this Logger will affect all of the log messages generated by the data source.
		''' In the worst case, this may be the root Logger.
		''' </summary>
		''' <returns> the parent Logger for this data source </returns>
		''' <exception cref="SQLFeatureNotSupportedException"> if the data source does not use
		''' {@code java.util.logging}
		''' @since 1.7 </exception>
		ReadOnly Property parentLogger As java.util.logging.Logger
	End Interface

End Namespace