Namespace org.omg.CosNaming

	''' <summary>
	''' org/omg/CosNaming/BindingIteratorHolder.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' The BindingIterator interface allows a client to iterate through
	''' the bindings using the next_one or next_n operations.
	''' 
	''' The bindings iterator is obtained by using the <tt>list</tt>
	''' method on the <tt>NamingContext</tt>. </summary>
	''' <seealso cref= org.omg.CosNaming.NamingContext#list </seealso>
	Public NotInheritable Class BindingIteratorHolder
		Implements org.omg.CORBA.portable.Streamable

	  Public value As org.omg.CosNaming.BindingIterator = Nothing

	  Public Sub New()
	  End Sub

	  Public Sub New(ByVal initialValue As org.omg.CosNaming.BindingIterator)
		value = initialValue
	  End Sub

	  Public Sub _read(ByVal i As org.omg.CORBA.portable.InputStream)
		value = org.omg.CosNaming.BindingIteratorHelper.read(i)
	  End Sub

	  Public Sub _write(ByVal o As org.omg.CORBA.portable.OutputStream)
		org.omg.CosNaming.BindingIteratorHelper.write(o, value)
	  End Sub

	  Public Function _type() As org.omg.CORBA.TypeCode
		Return org.omg.CosNaming.BindingIteratorHelper.type()
	  End Function

	End Class

End Namespace