Namespace org.omg.CosNaming


	''' <summary>
	''' org/omg/CosNaming/Binding.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public NotInheritable Class Binding
		Implements org.omg.CORBA.portable.IDLEntity

	  Public binding_name As org.omg.CosNaming.NameComponent() = Nothing

	  ' name
	  Public binding_type As org.omg.CosNaming.BindingType = Nothing

	  Public Sub New()
	  End Sub ' ctor

	  Public Sub New(ByVal _binding_name As org.omg.CosNaming.NameComponent(), ByVal _binding_type As org.omg.CosNaming.BindingType)
		binding_name = _binding_name
		binding_type = _binding_type
	  End Sub ' ctor

	End Class ' class Binding

End Namespace