Namespace org.omg.CosNaming


	''' <summary>
	''' org/omg/CosNaming/NamingContext.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' A naming context is an object that contains a set of name bindings in 
	''' which each name is unique. Different names can be bound to an object 
	''' in the same or different contexts at the same time. <p>
	''' 
	''' See <a href="http://www.omg.org/technology/documents/formal/naming_service.htm">
	''' CORBA COS 
	''' Naming Specification.</a>
	''' </summary>
	Public Interface NamingContext
		Inherits NamingContextOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity

	End Interface ' interface NamingContext

End Namespace