Namespace org.omg.CosNaming

	''' <summary>
	''' org/omg/CosNaming/NamingContextExtHolder.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' <code>NamingContextExt</code> is the extension of <code>NamingContext</code>
	''' which
	''' contains a set of name bindings in which each name is unique and is
	''' part of Interoperable Naming Service.
	''' Different names can be bound to an object in the same or different
	''' contexts at the same time. Using <tt>NamingContextExt</tt>, you can use
	''' URL-based names to bind and resolve. <p>
	''' 
	''' See <a href="http://www.omg.org/technology/documents/formal/naming_service.htm">
	''' CORBA COS 
	''' Naming Specification.</a>
	''' </summary>
	Public NotInheritable Class NamingContextExtHolder
		Implements org.omg.CORBA.portable.Streamable

	  Public value As org.omg.CosNaming.NamingContextExt = Nothing

	  Public Sub New()
	  End Sub

	  Public Sub New(ByVal initialValue As org.omg.CosNaming.NamingContextExt)
		value = initialValue
	  End Sub

	  Public Sub _read(ByVal i As org.omg.CORBA.portable.InputStream)
		value = org.omg.CosNaming.NamingContextExtHelper.read(i)
	  End Sub

	  Public Sub _write(ByVal o As org.omg.CORBA.portable.OutputStream)
		org.omg.CosNaming.NamingContextExtHelper.write(o, value)
	  End Sub

	  Public Function _type() As org.omg.CORBA.TypeCode
		Return org.omg.CosNaming.NamingContextExtHelper.type()
	  End Function

	End Class

End Namespace