Namespace org.omg.DynamicAny


	''' <summary>
	''' org/omg/DynamicAny/DynFixed.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' DynFixed objects support the manipulation of IDL fixed values.
	''' Because IDL does not have a generic type that can represent fixed types with arbitrary
	''' number of digits and arbitrary scale, the operations use the IDL string type.
	''' </summary>
	Public Interface DynFixed
		Inherits DynFixedOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity

	End Interface ' interface DynFixed

End Namespace