Namespace org.omg.DynamicAny


	''' <summary>
	''' org/omg/DynamicAny/DynValueCommon.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' DynValueCommon provides operations supported by both the DynValue and DynValueBox interfaces.
	''' </summary>
	Public Interface DynValueCommon
		Inherits DynValueCommonOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity

	End Interface ' interface DynValueCommon

End Namespace