Namespace org.omg.DynamicAny


	''' <summary>
	''' org/omg/DynamicAny/NameDynAnyPair.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public NotInheritable Class NameDynAnyPair
		Implements org.omg.CORBA.portable.IDLEntity

	  ''' <summary>
	  ''' The name associated with the DynAny.
	  ''' </summary>
	  Public id As String = Nothing

	  ''' <summary>
	  ''' The DynAny value associated with the name.
	  ''' </summary>
	  Public value As org.omg.DynamicAny.DynAny = Nothing

	  Public Sub New()
	  End Sub ' ctor

	  Public Sub New(ByVal _id As String, ByVal _value As org.omg.DynamicAny.DynAny)
		id = _id
		value = _value
	  End Sub ' ctor

	End Class ' class NameDynAnyPair

End Namespace