Namespace org.omg.IOP


	''' <summary>
	''' org/omg/IOP/CodeSets.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public Interface CodeSets

	  ''' <summary>
	  ''' Identifies a CDR encapsulation of the 
	  ''' <code>CONV_FRAME.CodeSetContext</code> defined in 
	  ''' Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
	  ''' </summary>
'JAVA TO VB CONVERTER TODO TASK: Interfaces cannot contain fields in .NET:
'	  public static final int value = (int)(1L);
	End Interface

End Namespace