Namespace org.omg.IOP


	''' <summary>
	''' org/omg/IOP/CodecOperations.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' The formats of IOR components and service context data used by ORB 
	''' services are often defined as CDR encapsulations encoding instances 
	''' of IDL defined data types. The <code>Codec</code> provides a mechanism 
	''' to transfer these components between their IDL data types and their CDR 
	''' encapsulation representations. 
	''' <p>
	''' A <code>Codec</code> is obtained from the <code>CodecFactory</code>. 
	''' The <code>CodecFactory</code> is obtained through a call to 
	''' <code>ORB.resolve_initial_references( "CodecFactory" )</code>.
	''' </summary>
	Public Interface CodecOperations

	  ''' <summary>
	  ''' Converts the given any into a byte array based on the encoding 
	  ''' format effective for this <code>Codec</code>. 
	  ''' </summary>
	  ''' <param name="data"> The data, in the form of an any, to be encoded into 
	  '''     a byte array. </param>
	  ''' <returns> A byte array containing the encoded Any. This byte array 
	  '''     contains both the <code>TypeCode</code> and the data of the type. </returns>
	  ''' <exception cref="InvalidTypeForEncoding"> thrown if the type is not valid for 
	  '''     the encoding format effective for this <code>Codec</code>. </exception>
	  Function encode(ByVal data As org.omg.CORBA.Any) As SByte()

	  ''' <summary>
	  ''' Decodes the given byte array into an Any based on the encoding 
	  ''' format effective for this <code>Codec</code>. 
	  ''' </summary>
	  ''' <param name="data"> The data, in the form of a byte array, to be decoded into 
	  '''     an Any. </param>
	  ''' <returns> An Any containing the data from the decoded byte array. </returns>
	  ''' <exception cref="FormatMismatch"> is thrown if the byte array cannot be 
	  '''     decoded into an Any.  </exception>
	  Function decode(ByVal data As SByte()) As org.omg.CORBA.Any

	  ''' <summary>
	  ''' Converts the given any into a byte array based on the encoding 
	  ''' format effective for this Codec. Only the data from the Any is 
	  ''' encoded, not the <code>TypeCode</code>. 
	  ''' </summary>
	  ''' <param name="data"> The data, in the form of an Any, to be encoded into 
	  '''     a byte array. </param>
	  ''' <returns> A byte array containing the data from the encoded any. </returns>
	  ''' <exception cref="InvalidTypeForEncoding"> thrown if the type is not valid for 
	  '''     the encoding format effective for this <code>Codec</code>. </exception>
	  Function encode_value(ByVal data As org.omg.CORBA.Any) As SByte()

	  ''' <summary>
	  ''' Decodes the given byte array into an Any based on the given 
	  ''' <code>TypeCode</code> and the encoding format effective for 
	  ''' this <code>Codec</code>. 
	  ''' </summary>
	  ''' <param name="data"> The data, in the form of a byte array, to be decoded 
	  '''     into an Any. </param>
	  ''' <param name="tc"> The TypeCode to be used to decode the data. </param>
	  ''' <returns> An Any containing the data from the decoded byte array. </returns>
	  ''' <exception cref="FormatMismatch"> thrown if the byte array cannot be 
	  '''     decoded into an Any.  </exception>
	  Function decode_value(ByVal data As SByte(), ByVal tc As org.omg.CORBA.TypeCode) As org.omg.CORBA.Any
	End Interface ' interface CodecOperations

End Namespace