Namespace org.omg.IOP


	''' <summary>
	''' org/omg/IOP/TAG_CODE_SETS.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public Interface TAG_CODE_SETS

	  ''' <summary>
	  ''' The code set component of the IOR multi-component profile structure
	  ''' contains:
	  ''' <ul>
	  '''   <li>server's native char code set and conversion code sets, and</li>
	  '''   <li>server's native wchar code set and conversion code sets.</li>
	  ''' </ul>
	  ''' Both char and wchar conversion code sets are listed in order of 
	  ''' preference.
	  ''' </summary>
'JAVA TO VB CONVERTER TODO TASK: Interfaces cannot contain fields in .NET:
'	  public static final int value = (int)(1L);
	End Interface

End Namespace