Imports System.Runtime.CompilerServices

Namespace org.omg.IOP


	''' <summary>
	''' org/omg/IOP/TaggedComponentHelper.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public MustInherit Class TaggedComponentHelper
	  Private Shared _id As String = "IDL:omg.org/IOP/TaggedComponent:1.0"

	  Public Shared Sub insert(ByVal a As org.omg.CORBA.Any, ByVal that As org.omg.IOP.TaggedComponent)
		Dim out As org.omg.CORBA.portable.OutputStream = a.create_output_stream()
		a.type(type())
		write(out, that)
		a.read_value(out.create_input_stream(), type())
	  End Sub

	  Public Shared Function extract(ByVal a As org.omg.CORBA.Any) As org.omg.IOP.TaggedComponent
		Return read(a.create_input_stream())
	  End Function

	  Private Shared __typeCode As org.omg.CORBA.TypeCode = Nothing
	  Private Shared __active As Boolean = False
	  <MethodImpl(MethodImplOptions.Synchronized)> _
	  Public Shared Function type() As org.omg.CORBA.TypeCode
		If __typeCode Is Nothing Then
		  SyncLock GetType(org.omg.CORBA.TypeCode)
			If __typeCode Is Nothing Then
			  If __active Then Return org.omg.CORBA.ORB.init().create_recursive_tc(_id)
			  __active = True
			  Dim _members0 As org.omg.CORBA.StructMember() = New org.omg.CORBA.StructMember (1){}
			  Dim _tcOf_members0 As org.omg.CORBA.TypeCode = Nothing
			  _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_ulong)
			  _tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(org.omg.IOP.ComponentIdHelper.id(), "ComponentId", _tcOf_members0)
			  _members0(0) = New org.omg.CORBA.StructMember("tag", _tcOf_members0, Nothing)
			  _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_octet)
			  _tcOf_members0 = org.omg.CORBA.ORB.init().create_sequence_tc(0, _tcOf_members0)
			  _members0(1) = New org.omg.CORBA.StructMember("component_data", _tcOf_members0, Nothing)
			  __typeCode = org.omg.CORBA.ORB.init().create_struct_tc(org.omg.IOP.TaggedComponentHelper.id(), "TaggedComponent", _members0)
			  __active = False
			End If
		  End SyncLock
		End If
		Return __typeCode
	  End Function

	  Public Shared Function id() As String
		Return _id
	  End Function

	  Public Shared Function read(ByVal istream As org.omg.CORBA.portable.InputStream) As org.omg.IOP.TaggedComponent
		Dim value As New org.omg.IOP.TaggedComponent
		value.tag = istream.read_ulong()
		Dim _len0 As Integer = istream.read_long()
		value.component_data = New SByte(_len0 - 1){}
		istream.read_octet_array(value.component_data, 0, _len0)
		Return value
	  End Function

	  Public Shared Sub write(ByVal ostream As org.omg.CORBA.portable.OutputStream, ByVal value As org.omg.IOP.TaggedComponent)
		ostream.write_ulong(value.tag)
		ostream.write_long(value.component_data.Length)
		ostream.write_octet_array(value.component_data, 0, value.component_data.Length)
	  End Sub

	End Class

End Namespace