Imports System.Runtime.CompilerServices

'
' * Copyright (c) 2001, Oracle and/or its affiliates. All rights reserved.
' * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' 

Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/CurrentHelper.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.1"
	''' from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
	''' Tuesday, October 23, 2001 1:17:01 PM PDT
	''' </summary>


	''' <summary>
	''' The PortableServer::Current interface, derived from
	''' CORBA::Current, provides method implementations with
	''' access to the identity of the object on which the
	''' method was invoked. The Current interface is provided
	''' to support servants that implement multiple objects,
	''' but can be used within the context of POA-dispatched
	''' method invocations on any servant. To provide location
	''' transparency, ORBs are required to support use of
	''' Current in the context of both locally and remotely
	''' invoked operations. An instance of Current can be
	''' obtained by the application by issuing the
	''' CORBA::ORB::resolve_initial_references("POACurrent")
	''' operation. Thereafter, it can be used within the
	''' context of a method dispatched by the POA to obtain
	''' the POA and ObjectId that identify the object on
	''' which that operation was invoked.
	''' </summary>
	Public MustInherit Class CurrentHelper
		Private Shared _id As String = "IDL:omg.org/PortableServer/Current:2.3"

		Public Shared Sub insert(ByVal a As org.omg.CORBA.Any, ByVal that As org.omg.PortableServer.Current)
			Dim out As org.omg.CORBA.portable.OutputStream = a.create_output_stream()
			a.type(type())
			write(out, that)
			a.read_value(out.create_input_stream(), type())
		End Sub

		Public Shared Function extract(ByVal a As org.omg.CORBA.Any) As org.omg.PortableServer.Current
			Return read(a.create_input_stream())
		End Function

		Private Shared __typeCode As org.omg.CORBA.TypeCode = Nothing
		<MethodImpl(MethodImplOptions.Synchronized)> _
		Public Shared Function type() As org.omg.CORBA.TypeCode
			If __typeCode Is Nothing Then __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(org.omg.PortableServer.CurrentHelper.id(), "Current")
			Return __typeCode
		End Function

		Public Shared Function id() As String
			Return _id
		End Function

		Public Shared Function read(ByVal istream As org.omg.CORBA.portable.InputStream) As org.omg.PortableServer.Current
			Throw New org.omg.CORBA.MARSHAL
		End Function

		Public Shared Sub write(ByVal ostream As org.omg.CORBA.portable.OutputStream, ByVal value As org.omg.PortableServer.Current)
			Throw New org.omg.CORBA.MARSHAL
		End Sub

		Public Shared Function narrow(ByVal obj As org.omg.CORBA.Object) As org.omg.PortableServer.Current
			If obj Is Nothing Then
				Return Nothing
			ElseIf TypeOf obj Is org.omg.PortableServer.Current Then
				Return CType(obj, org.omg.PortableServer.Current)
			ElseIf Not obj._is_a(id()) Then
				Throw New org.omg.CORBA.BAD_PARAM
			End If
			Return Nothing
		End Function

	End Class

End Namespace