Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/ForwardRequest.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public NotInheritable Class ForwardRequest
		Inherits org.omg.CORBA.UserException

	  Public forward_reference As org.omg.CORBA.Object = Nothing

	  Public Sub New()
		MyBase.New(ForwardRequestHelper.id())
	  End Sub ' ctor

	  Public Sub New(ByVal _forward_reference As org.omg.CORBA.Object)
		MyBase.New(ForwardRequestHelper.id())
		forward_reference = _forward_reference
	  End Sub ' ctor


	  Public Sub New(ByVal $reason As String, ByVal _forward_reference As org.omg.CORBA.Object)
		MyBase.New(ForwardRequestHelper.id() & "  " & $reason)
		forward_reference = _forward_reference
	  End Sub ' ctor

	End Class ' class ForwardRequest

End Namespace