Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/IdAssignmentPolicyOperations.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' IdAssignmentPolicy specifies whether Object Ids in 
	''' the created POA are generated by the application or 
	''' by the ORB. The default is SYSTEM_ID.
	''' </summary>
	Public Interface IdAssignmentPolicyOperations
		Inherits org.omg.CORBA.PolicyOperations

	  ''' <summary>
	  ''' specifies the policy value
	  ''' </summary>
	  Function value() As org.omg.PortableServer.IdAssignmentPolicyValue
	End Interface ' interface IdAssignmentPolicyOperations

End Namespace