Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/LifespanPolicyValue.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' The LifespanPolicyValue can have the following values.
	''' TRANSIENT - The objects implemented in the POA 
	''' cannot outlive the POA instance in which they are 
	''' first created. 
	''' PERSISTENT - The objects implemented in the POA can 
	''' outlive the process in which they are first created. 
	''' </summary>
	Public Class LifespanPolicyValue
		Implements org.omg.CORBA.portable.IDLEntity

	  Private __value As Integer
	  Private Shared __size As Integer = 2
	  Private Shared __array As org.omg.PortableServer.LifespanPolicyValue() = New org.omg.PortableServer.LifespanPolicyValue (__size - 1){}

	  Public Const _TRANSIENT As Integer = 0
	  Public Shared ReadOnly TRANSIENT As New org.omg.PortableServer.LifespanPolicyValue(_TRANSIENT)
	  Public Const _PERSISTENT As Integer = 1
	  Public Shared ReadOnly PERSISTENT As New org.omg.PortableServer.LifespanPolicyValue(_PERSISTENT)

	  Public Overridable Function value() As Integer
		Return __value
	  End Function

	  Public Shared Function from_int(ByVal value As Integer) As org.omg.PortableServer.LifespanPolicyValue
		If value >= 0 AndAlso value < __size Then
		  Return __array(value)
		Else
		  Throw New org.omg.CORBA.BAD_PARAM
		End If
	  End Function

	  Protected Friend Sub New(ByVal value As Integer)
		__value = value
		__array(__value) = Me
	  End Sub
	End Class ' class LifespanPolicyValue

End Namespace