Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/POAManager.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' Each POA object has an associated POAManager object. 
	''' A POA manager may be associated with one or more 
	''' POA objects. A POA manager encapsulates the processing 
	''' state of the POAs it is associated with.
	''' </summary>
	Public Interface POAManager
		Inherits POAManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity

	End Interface ' interface POAManager

End Namespace