Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/ServantRetentionPolicy.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' This policy specifies whether the created POA retains 
	''' active servants in an Active Object Map. 
	''' </summary>
	Public Interface ServantRetentionPolicy
		Inherits ServantRetentionPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity

	End Interface ' interface ServantRetentionPolicy

End Namespace