Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/ServantManagerOperations.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' A servant manager supplies a POA with the ability 
	''' to activate objects on demand when the POA receives 
	''' a request targeted at an inactive object. A servant 
	''' manager is registered with a POA as a callback object, 
	''' to be invoked by the POA when necessary.
	''' ServantManagers can either be ServantActivators or
	''' ServantLocators. A ServantManager object must be 
	''' local to the process containing the POA objects 
	''' it is registered with.
	''' </summary>
	Public Interface ServantManagerOperations
	End Interface ' interface ServantManagerOperations

End Namespace