Namespace org.omg.PortableServer


	''' <summary>
	''' org/omg/PortableServer/SERVANT_RETENTION_POLICY_ID.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public Interface SERVANT_RETENTION_POLICY_ID

	  ''' <summary>
	  ''' The value representing SERVANT_RETENTION_POLICY_ID.
	  ''' </summary>
'JAVA TO VB CONVERTER TODO TASK: Interfaces cannot contain fields in .NET:
'	  public static final int value = (int)(21L);
	End Interface

End Namespace