Imports System

' Stub class generated by rmic, do not edit.
' Contents subject to change without notice.

Namespace javax.management.remote.rmi

	Public NotInheritable Class RMIServerImpl_Stub
		Inherits java.rmi.server.RemoteStub
		Implements javax.management.remote.rmi.RMIServer

		Private Const serialVersionUID As Long = 2

		Private Shared $method_getVersion_0 As System.Reflection.MethodInfo
		Private Shared $method_newClient_1 As System.Reflection.MethodInfo

		Shared Sub New()
		Try
			$method_getVersion_0 = GetType(javax.management.remote.rmi.RMIServer).getMethod("getVersion", New Type() {})
			$method_newClient_1 = GetType(javax.management.remote.rmi.RMIServer).getMethod("newClient", New Type() {GetType(Object)})
		Catch e As java.lang.NoSuchMethodException
			Throw New System.MissingMethodException("stub class initialization failed")
		End Try
		End Sub

		' constructors
		Public Sub New(ByVal ref As java.rmi.server.RemoteRef)
		MyBase.New(ref)
		End Sub

		' methods from remote interfaces

		' implementation of getVersion()
		Public Property version As String
			Get
			Try
				Dim $result As Object = ref.invoke(Me, $method_getVersion_0, Nothing, -8081107751519807347L)
				Return (CStr($result))
			Catch e As Exception
				Throw e
			Catch e As java.rmi.RemoteException
				Throw e
			Catch e As Exception
				Throw New java.rmi.UnexpectedException("undeclared checked exception", e)
			End Try
			End Get
		End Property

		' implementation of newClient(Object)
		Public Function newClient(ByVal $param_Object_1 As Object) As javax.management.remote.rmi.RMIConnection
		Try
			Dim $result As Object = ref.invoke(Me, $method_newClient_1, New Object() {$param_Object_1}, -1089742558549201240L)
			Return (CType($result, javax.management.remote.rmi.RMIConnection))
		Catch e As Exception
			Throw e
		Catch e As java.io.IOException
			Throw e
		Catch e As Exception
			Throw New java.rmi.UnexpectedException("undeclared checked exception", e)
		End Try
		End Function
	End Class

End Namespace