'
' * Copyright (c) 1996, 2013, Oracle and/or its affiliates. All rights reserved.
' * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' 

Namespace java.awt.event


	''' <summary>
	''' A low-level event which indicates that a container's contents
	''' changed because a component was added or removed.
	''' <P>
	''' Container events are provided for notification purposes ONLY;
	''' The AWT will automatically handle changes to the containers
	''' contents internally so that the program works properly regardless of
	''' whether the program is receiving these events or not.
	''' <P>
	''' This low-level event is generated by a container object (such as a
	''' Panel) when a component is added to it or removed from it.
	''' The event is passed to every <code>ContainerListener</code>
	''' or <code>ContainerAdapter</code> object which registered to receive such
	''' events using the component's <code>addContainerListener</code> method.
	''' (<code>ContainerAdapter</code> objects implement the
	''' <code>ContainerListener</code> interface.) Each such listener object
	''' gets this <code>ContainerEvent</code> when the event occurs.
	''' <p>
	''' An unspecified behavior will be caused if the {@code id} parameter
	''' of any particular {@code ContainerEvent} instance is not
	''' in the range from {@code CONTAINER_FIRST} to {@code CONTAINER_LAST}.
	''' </summary>
	''' <seealso cref= ContainerAdapter </seealso>
	''' <seealso cref= ContainerListener </seealso>
	''' <seealso cref= <a href="https://docs.oracle.com/javase/tutorial/uiswing/events/containerlistener.html">Tutorial: Writing a Container Listener</a>
	''' 
	''' @author Tim Prinzing
	''' @author Amy Fowler
	''' @since 1.1 </seealso>
	Public Class ContainerEvent
		Inherits ComponentEvent

		''' <summary>
		''' The first number in the range of ids used for container events.
		''' </summary>
		Public Const CONTAINER_FIRST As Integer = 300

		''' <summary>
		''' The last number in the range of ids used for container events.
		''' </summary>
		Public Const CONTAINER_LAST As Integer = 301

	   ''' <summary>
	   ''' This event indicates that a component was added to the container.
	   ''' </summary>
		Public Const COMPONENT_ADDED As Integer = CONTAINER_FIRST

		''' <summary>
		''' This event indicates that a component was removed from the container.
		''' </summary>
		Public Shared ReadOnly COMPONENT_REMOVED As Integer = 1 + CONTAINER_FIRST

		''' <summary>
		''' The non-null component that is being added or
		''' removed from the Container.
		''' 
		''' @serial </summary>
		''' <seealso cref= #getChild() </seealso>
		Friend child As java.awt.Component

	'    
	'     * JDK 1.1 serialVersionUID
	'     
		Private Const serialVersionUID As Long = -4114942250539772041L

		''' <summary>
		''' Constructs a <code>ContainerEvent</code> object.
		''' <p> This method throws an
		''' <code>IllegalArgumentException</code> if <code>source</code>
		''' is <code>null</code>.
		''' </summary>
		''' <param name="source"> The <code>Component</code> object (container)
		'''               that originated the event </param>
		''' <param name="id">     An integer indicating the type of event.
		'''                     For information on allowable values, see
		'''                     the class description for <seealso cref="ContainerEvent"/> </param>
		''' <param name="child">  the component that was added or removed </param>
		''' <exception cref="IllegalArgumentException"> if <code>source</code> is null </exception>
		''' <seealso cref= #getContainer() </seealso>
		''' <seealso cref= #getID() </seealso>
		''' <seealso cref= #getChild() </seealso>
		Public Sub New(  source As java.awt.Component,   id As Integer,   child As java.awt.Component)
			MyBase.New(source, id)
			Me.child = child
		End Sub

		''' <summary>
		''' Returns the originator of the event.
		''' </summary>
		''' <returns> the <code>Container</code> object that originated
		''' the event, or <code>null</code> if the object is not a
		''' <code>Container</code>. </returns>
		Public Overridable Property container As java.awt.Container
			Get
				Return If(TypeOf source Is java.awt.Container, CType(source, java.awt.Container), Nothing)
			End Get
		End Property

		''' <summary>
		''' Returns the component that was affected by the event.
		''' </summary>
		''' <returns> the Component object that was added or removed </returns>
		Public Overridable Property child As java.awt.Component
			Get
				Return child
			End Get
		End Property

		''' <summary>
		''' Returns a parameter string identifying this event.
		''' This method is useful for event-logging and for debugging.
		''' </summary>
		''' <returns> a string identifying the event and its attributes </returns>
		Public Overrides Function paramString() As String
			Dim typeStr As String
			Select Case id
			  Case COMPONENT_ADDED
				  typeStr = "COMPONENT_ADDED"
			  Case COMPONENT_REMOVED
				  typeStr = "COMPONENT_REMOVED"
			  Case Else
				  typeStr = "unknown type"
			End Select
			Return typeStr & ",child=" & child.name
		End Function
	End Class

End Namespace