'
' * Copyright (c) 1999, 2001, Oracle and/or its affiliates. All rights reserved.
' * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' 
Namespace org.omg.CORBA


	''' <summary>
	''' The interface for <tt>Current</tt>.  For more information on
	''' Operations interfaces, see <a href="doc-files/generatedfiles.html">
	''' "Generated Files"</a>.
	''' 
	''' org/omg/CORBA/CurrentOperations.java
	''' Generated by the IDL-to-Java compiler (portable), version "3.0"
	''' from ../../../../../src/share/classes/org/omg/PortableServer/corba.idl
	''' Saturday, July 17, 1999 12:26:21 AM PDT.
	''' </summary>

	Public Interface CurrentOperations
	End Interface ' interface CurrentOperations

End Namespace