'
' * Copyright (c) 1999, 2001, Oracle and/or its affiliates. All rights reserved.
' * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' 
Namespace org.omg.CORBA

	''' <summary>
	''' The interface for <tt>IDLType</tt>.  For more information on
	''' Operations interfaces, see <a href="doc-files/generatedfiles.html#operations">
	''' "Generated Files: Operations files"</a>.
	''' </summary>

	'
	' tempout/org/omg/CORBA/IDLTypeOperations.java
	' Generated by the IBM IDL-to-Java compiler, version 1.0
	' from ../../Lib/ir.idl
	' Thursday, February 25, 1999 2:11:23 o'clock PM PST
	'

	''' <summary>
	''' This interface must be implemented by all IDLType objects.
	''' The IDLType is inherited by all IR objects that
	''' represent IDL types, including interfaces, typedefs, and
	''' anonymous types. </summary>
	''' <seealso cref= IDLType </seealso>
	''' <seealso cref= IRObject </seealso>
	''' <seealso cref= IRObjectOperations </seealso>

	Public Interface IDLTypeOperations
		Inherits org.omg.CORBA.IRObjectOperations

		''' <summary>
		''' The type attribute describes the type defined by an object
		''' derived from <code>IDLType</code>. </summary>
		''' <returns> the <code>TypeCode</code> defined by this object. </returns>
		Function type() As org.omg.CORBA.TypeCode
	End Interface ' interface IDLTypeOperations

End Namespace