Namespace org.omg.CORBA


	''' <summary>
	''' org/omg/CORBA/StringSeqHolder.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/CORBAX.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' An array of Strings </summary>
	Public NotInheritable Class StringSeqHolder
		Implements org.omg.CORBA.portable.Streamable

	  Public value As String() = Nothing

	  Public Sub New()
	  End Sub

	  Public Sub New(ByVal initialValue As String())
		value = initialValue
	  End Sub

	  Public Sub _read(ByVal i As org.omg.CORBA.portable.InputStream)
		value = org.omg.CORBA.StringSeqHelper.read(i)
	  End Sub

	  Public Sub _write(ByVal o As org.omg.CORBA.portable.OutputStream)
		org.omg.CORBA.StringSeqHelper.write(o, value)
	  End Sub

	  Public Function _type() As org.omg.CORBA.TypeCode
		Return org.omg.CORBA.StringSeqHelper.type()
	  End Function

	End Class

End Namespace