Imports System.Runtime.CompilerServices

'
' * Copyright (c) 1999, 2001, Oracle and/or its affiliates. All rights reserved.
' * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' *
' 
Namespace org.omg.CORBA


	''' <summary>
	''' The Helper for <tt>Visibility</tt>.  For more information on
	''' Helper files, see <a href="doc-files/generatedfiles.html#helper">
	''' "Generated Files: Helper Files"</a>.<P>
	''' org/omg/CORBA/VisibilityHelper.java
	''' Generated by the IDL-to-Java compiler (portable), version "3.0"
	''' from ir.idl
	''' 03 June 1999 11:33:44 o'clock GMT+00:00
	''' </summary>


	' orbos 98-01-18: Objects By Value -- begin
	Public MustInherit Class VisibilityHelper
	  Private Shared _id As String = "IDL:omg.org/CORBA/Visibility:1.0"

	  Public Shared Sub insert(ByVal a As org.omg.CORBA.Any, ByVal that As Short)
		Dim out As org.omg.CORBA.portable.OutputStream = a.create_output_stream()
		a.type(type())
		write(out, that)
		a.read_value(out.create_input_stream(), type())
	  End Sub

	  Public Shared Function extract(ByVal a As org.omg.CORBA.Any) As Short
		Return read(a.create_input_stream())
	  End Function

	  Private Shared __typeCode As org.omg.CORBA.TypeCode = Nothing
	  <MethodImpl(MethodImplOptions.Synchronized)> _
	  Public Shared Function type() As org.omg.CORBA.TypeCode
		If __typeCode Is Nothing Then
		  __typeCode = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_short)
		  __typeCode = org.omg.CORBA.ORB.init().create_alias_tc(org.omg.CORBA.VisibilityHelper.id(), "Visibility", __typeCode)
		End If
		Return __typeCode
	  End Function

	  Public Shared Function id() As String
		Return _id
	  End Function

	  Public Shared Function read(ByVal istream As org.omg.CORBA.portable.InputStream) As Short
		Dim value As Short = CShort(0)
		value = istream.read_short()
		Return value
	  End Function

	  Public Shared Sub write(ByVal ostream As org.omg.CORBA.portable.OutputStream, ByVal value As Short)
		ostream.write_short(value)
	  End Sub

	End Class

End Namespace