Imports System.Runtime.CompilerServices

Namespace org.omg.PortableInterceptor


	''' <summary>
	''' org/omg/PortableInterceptor/CurrentHelper.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' Portable Interceptors Current (also known as <code>PICurrent</code>) 
	''' is merely a slot table, the slots of which are used by each service to 
	''' transfer their context data between their context and the request's or 
	''' reply's service context. Each service which wishes to use PICurrent 
	''' reserves a slot or slots at initialization time and uses those slots 
	''' during the processing of requests and replies.
	''' <p>
	''' Before an invocation is made, PICurrent is obtained via a call to 
	''' <code>ORB.resolve_initial_references( "PICurrent" )</code>. From within 
	''' the interception points, the data on PICurrent that has moved from the 
	''' thread scope to the request scope is available via the 
	''' <code>get_slot</code> operation on the <code>RequestInfo</code> object. 
	''' A PICurrent can still be obtained via 
	''' <code>resolve_initial_references</code>, but that is the Interceptor's 
	''' thread scope PICurrent.
	''' </summary>
	Public MustInherit Class CurrentHelper
	  Private Shared _id As String = "IDL:omg.org/PortableInterceptor/Current:1.0"

	  Public Shared Sub insert(ByVal a As org.omg.CORBA.Any, ByVal that As org.omg.PortableInterceptor.Current)
		Dim out As org.omg.CORBA.portable.OutputStream = a.create_output_stream()
		a.type(type())
		write(out, that)
		a.read_value(out.create_input_stream(), type())
	  End Sub

	  Public Shared Function extract(ByVal a As org.omg.CORBA.Any) As org.omg.PortableInterceptor.Current
		Return read(a.create_input_stream())
	  End Function

	  Private Shared __typeCode As org.omg.CORBA.TypeCode = Nothing
	  <MethodImpl(MethodImplOptions.Synchronized)> _
	  Public Shared Function type() As org.omg.CORBA.TypeCode
		If __typeCode Is Nothing Then __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(org.omg.PortableInterceptor.CurrentHelper.id(), "Current")
		Return __typeCode
	  End Function

	  Public Shared Function id() As String
		Return _id
	  End Function

	  Public Shared Function read(ByVal istream As org.omg.CORBA.portable.InputStream) As org.omg.PortableInterceptor.Current
		  Throw New org.omg.CORBA.MARSHAL
	  End Function

	  Public Shared Sub write(ByVal ostream As org.omg.CORBA.portable.OutputStream, ByVal value As org.omg.PortableInterceptor.Current)
		  Throw New org.omg.CORBA.MARSHAL
	  End Sub

	  Public Shared Function narrow(ByVal obj As org.omg.CORBA.Object) As org.omg.PortableInterceptor.Current
		If obj Is Nothing Then
		  Return Nothing
		ElseIf TypeOf obj Is org.omg.PortableInterceptor.Current Then
		  Return CType(obj, org.omg.PortableInterceptor.Current)
		Else
		  Throw New org.omg.CORBA.BAD_PARAM
		End If
	  End Function

	  Public Shared Function unchecked_narrow(ByVal obj As org.omg.CORBA.Object) As org.omg.PortableInterceptor.Current
		If obj Is Nothing Then
		  Return Nothing
		ElseIf TypeOf obj Is org.omg.PortableInterceptor.Current Then
		  Return CType(obj, org.omg.PortableInterceptor.Current)
		Else
		  Throw New org.omg.CORBA.BAD_PARAM
		End If
	  End Function

	End Class

End Namespace