Namespace org.omg.PortableInterceptor


	''' <summary>
	''' org/omg/PortableInterceptor/DISCARDING.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public Interface DISCARDING

	  ''' <summary>
	  ''' Object adapter state that causes all requests to be discarded.
	  ''' </summary>
'JAVA TO VB CONVERTER TODO TASK: Interfaces cannot contain fields in .NET:
'	  public static final short value = (short)(2);
	End Interface

End Namespace