Namespace org.omg.PortableInterceptor


	''' <summary>
	''' org/omg/PortableInterceptor/IORInterceptor_3_0Operations.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public Interface IORInterceptor_3_0Operations
		Inherits org.omg.PortableInterceptor.IORInterceptorOperations

	  ''' <summary>
	  ''' The components_established method is invoked on all registered 
	  ''' IORInterceptor_3_0 instances after establish_components
	  ''' has been invoked on all registered IORInterceptor instances.
	  ''' The adapter_template is available in info during this call.
	  ''' The current_factory may be get or set in info during this call.
	  ''' <p>
	  ''' Any exception thrown from this method is handled by the Object 
	  ''' Adapter that called this interceptor.  In the case of the POA,
	  ''' an exception results in a OBJ_ADAPTER exception with an OMG
	  ''' standard minor code of 6. </summary>
	  ''' <param name="info"> The IORInfo for the object adapter being created. </param>
	  Sub components_established(ByVal info As org.omg.PortableInterceptor.IORInfo)

	  ''' <summary>
	  ''' Called whenever the state of an adapter manager changes.
	  ''' For the POA, that is the POAManager.  If the state change
	  ''' is reported through <code>adapter_manager_state_changed</code>,
	  ''' it is not reported through <code>adapter_state_changed</code>. </summary>
	  ''' <param name="id"> the adapter manager id of the adapter manager that 
	  ''' changed state </param>
	  ''' <param name="state"> the new state of the adapter manager </param>
	  Sub adapter_manager_state_changed(ByVal id As Integer, ByVal state As Short)

	  ''' <summary>
	  ''' Called whenever the state of an object adapter changes, and
	  ''' the state change is not caused by an adapter manager.  Such
	  ''' changes are reported to all registered <code>IORInterceptor_3_0</code> 
	  ''' instances. </summary>
	  ''' <param name="templates"> the sequence of <code>ObjectReferenceTemplate</code> instances
	  '''     on which this state change occurred. </param>
	  ''' <param name="state"> the new <code>AdapterState</code> shared by all of the templates. </param>
	  Sub adapter_state_changed(ByVal templates As org.omg.PortableInterceptor.ObjectReferenceTemplate(), ByVal state As Short)
	End Interface ' interface IORInterceptor_3_0Operations

End Namespace