Namespace org.omg.PortableInterceptor


	''' <summary>
	''' org/omg/PortableInterceptor/ObjectReferenceFactory.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>


	''' <summary>
	''' The object reference factory.  This provides the capability of
	''' creating an object reference.
	''' </summary>
	Public Interface ObjectReferenceFactory
		Inherits org.omg.CORBA.portable.ValueBase

	  ''' <summary>
	  ''' make_object creates a CORBA object reference according
	  ''' to the data in this template, with the given repository ID and
	  ''' object ID.
	  ''' </summary>
	  Function make_object(ByVal repositoryId As String, ByVal object_id As SByte()) As org.omg.CORBA.Object

	End Interface ' interface ObjectReferenceFactory

End Namespace