Namespace org.omg.PortableInterceptor


	''' <summary>
	''' org/omg/PortableInterceptor/SYSTEM_EXCEPTION.java .
	''' Generated by the IDL-to-Java compiler (portable), version "3.2"
	''' from d:/re/puppet/workspace/8-2-build-windows-amd64-cygwin/jdk8u73/6086/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
	''' Friday, January 29, 2016 5:40:18 PM PST
	''' </summary>

	Public Interface SYSTEM_EXCEPTION

	  ''' <summary>
	  ''' Indicates a SystemException reply status. One possible value for 
	  ''' <code>RequestInfo.reply_status</code>. </summary>
	  ''' <seealso cref= RequestInfo#reply_status </seealso>
	  ''' <seealso cref= SUCCESSFUL </seealso>
	  ''' <seealso cref= USER_EXCEPTION </seealso>
	  ''' <seealso cref= LOCATION_FORWARD </seealso>
	  ''' <seealso cref= TRANSPORT_RETRY </seealso>
'JAVA TO VB CONVERTER TODO TASK: Interfaces cannot contain fields in .NET:
'	  public static final short value = (short)(1);
	End Interface

End Namespace